# Generated by Django 5.1.6 on 2025-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
